security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            provider: app_user_provider
            access_denied_handler: App\Security\AccessDeniedHandler
            custom_authenticator: App\Security\AppProfileAuthenticator
            user_checker: App\Security\UserChecker
            logout:
                path: app_logout

        admin:
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
